image: node:14-alpine

stages:
  - build
  - test
build:
  stage: build
  tags:
    - docker
  script:
    - npm install
test:
  stage: test
  tags:
    - docker
  services:
    - name: mvertes/alpine-mongo:latest
      alias: mongo
  variables:
    MONGODB_URI: "mongodb://mongo:27017/serverTestDB"
  script:
    - npm install
    - npm test
